### ISSUE TITLE
Script.before_process() wrongly triggered at the 'txt2img' mode

### ISSUE THREAD

**Issue by LIU-Yinyi** [djbielejeski/a-person-mask-generator#1]
|**Environment**|**Version**|
|---|---|
|Stable Diffusion| v1.6.0-2-g4afaaf8a|
|A Person Mask Generator| commit: [04cad56](https://github.com/djbielejeski/a-person-mask-generator/commit/04cad56ffb0194bcb0040ea7f58cf186251296d3)|

At the `img2img` mode, it works perfectly. But when clicking `Generate` button at the `txt2img` tab, it will trigger an error:

```bash
*** Error running before_process: \path\to\StableDiffusion\stable-diffusion-webui\extensions\a-person-mask-generator\scripts\a_person_mask_generator.py
    Traceback (most recent call last):
      File "\path\to\StableDiffusion\stable-diffusion-webui\modules\scripts.py", line 611, in before_process
        script.before_process(p, *script_args)
    TypeError: Script.before_process() missing 2 required positional arguments: 'enabled' and 'mask_targets'
```

It seems that the bug is caused by no arguments to submit at the `txt2img` mode while `before_process()` is wrongly triggered to require two non-exist arguments. May fix it by adding a tab/mode check.

**Comment by djbielejeski** [comment]
@LIU-Yinyi this has been fixed.  Thanks for creating the issue!
