### ISSUE TITLE
Request for Background Color Customization Option

### ISSUE THREAD

**Issue by Vitali774** [djbielejeski/a-person-mask-generator#10]
This is not an issue but more like a request. Can we have options to set (assuming the background-only option is chosen) the background color to be solid white, black, chroma green (#00b140), or chroma blue (#0047BB) instead of a randomly generated background from prompts?

**Comment by djbielejeski** [comment]
Can you describe your use case and how this would add value?

All this extension does is create a Black and White mask

**Comment by Vitali774** [comment]
Hello David, thank you for your quick reply. The primary use will be for post-processing in other applications like Photoshop and Illustrator. Since your "masterpiece" produces very high-quality results by regenerating the entire image, this level of quality cannot be achieved using Photoshop's masking feature alone (it's very time-consuming). Having the ability to easily select the subject in an external application will greatly improve the workflow after using SD. I tried to achieve it using the prompt, but even with prompt weighting and the use of the in-paint model, the results are less than ideal, to say the least. It often attempts to fill the space with random content from the source generation.

**Comment by djbielejeski** [comment]
@Vitali774 Would you use a tool for generating these masks for post processing outside of Automatic1111? Aka a standalone python script could be made relatively quickly for this that could allow different colors for each selected mask.

**Comment by Vitali774** [comment]
I will try to explain with pictures. Images from left to right:

1.Generated image.
2.Generated image with your mask applied and the prompt set to "white wall."
3.Photoshop image with your generated mask applied separately.

Please notice the quality of the edges. When I generate an image inside img2img with your mask applied, the result is completely different because SD tries to regenerate a significant part of the image with too much new background. As of now, PNG files have very rough edges, so they are not really useful outside of automatic processing.

![758](https://github.com/djbielejeski/a-person-mask-generator/assets/125589442/5e867b85-fb78-4b3f-a2cd-3316c15ad746)

**Comment by Vitali774** [comment]
This is essentially how I envision it, with the options being "none (default)," white, black, green, and blue for background customization.
![Untitled-2](https://github.com/djbielejeski/a-person-mask-generator/assets/125589442/34383a17-6b41-496b-86f3-daa1ead0de11)

**Comment by djbielejeski** [comment]
I don't think building this into the tool would be helpful for general use.  You can download the preview and perform those edits and upload the mask into SD manually using the "Inpaint upload" feature.

**Comment by djbielejeski** [comment]
@Vitali774 I made you something

https://davidbielejeski.com/segment-image

![image](https://github.com/djbielejeski/a-person-mask-generator/assets/2463282/20f12bc8-a0c0-4727-9b1a-ac09e873292e)

**Comment by Vitali774** [comment]
That's perfect! Thank you a lot, David. I appreciate your help. I suggest you try Compy UI (if you haven't already). They offer numerous possibilities with custom nodes.

________________________________
