### ISSUE TITLE
Looking forward to detect head accessories

### ISSUE THREAD

**Issue by arafatx** [djbielejeski/a-person-mask-generator#13]
Very nice plugin that can Identify faces and hair. Is it possible in the future it can detect head accessories like scarf or hijab

Thank you.

**Comment by ArnorWing** [comment]
Great extension. 
Hand detection would be really good too if possible?

**Comment by djbielejeski** [comment]
Can you give me an example image to test against?  

It looks like the model has support for "accessories" that I did not expose in the UI

![image](https://github.com/djbielejeski/a-person-mask-generator/assets/2463282/d13e80f0-a555-4dab-9cd5-a7c632d83c61)

https://developers.google.com/mediapipe/solutions/vision/image_segmenter#multiclass-model
