### ISSUE TITLE
Do you plan to expand access via API?

### ISSUE THREAD

**Issue by godsgo** [djbielejeski/a-person-mask-generator#14]
Hello, thanks for your nice job.
Do you plan to expand access via API? 
For example send result mask as base64 png transparent image, thanks in advance...

**Comment by slonce70** [comment]
Is everything working fine for you now!? Maybe I'm doing something wrong!? My api is not working properly, but in the browser it's fine.

**Comment by djbielejeski** [comment]
See https://github.com/djbielejeski/a-person-mask-generator/issues/9
