### ISSUE TITLE
Failed to detect a face with glasses

### ISSUE THREAD

**Issue by arafatx** [djbielejeski/a-person-mask-generator#15]
I've experimented with several photos of a person wearing glasses, and seems like most of the time, the glasses are not included in the final output. Perhaps we could consider adding a new category as 'face accessories' ?

Here is a mask example taken from a person with glasses:

![image](https://github.com/djbielejeski/a-person-mask-generator/assets/4420157/44813021-d8a6-4d83-a1be-e6da0311343c)

Thank you.

**Comment by djbielejeski** [comment]
This isn't my segment model, its from MediaPipe (Google): https://developers.google.com/mediapipe/solutions/vision/image_segmenter#multiclass-model
