### ISSUE TITLE
A request

### ISSUE THREAD

**Issue by fonik000** [djbielejeski/a-person-mask-generator#18]
Can you add an upload function?
Where:
At the mask preview.
Why:
So that you can edit the mask  (example: photoshop) and then upload it.

**Comment by djbielejeski** [comment]
Just upload your own mask via the inpaint upload tab

![image](https://github.com/djbielejeski/a-person-mask-generator/assets/2463282/0b27fbc1-393c-4f01-a3fc-0006ba6cd47d)

**Comment by fonik000** [comment]
thanks, that works too. But it would be more practical if you could upload directly on the mask. or if you could paint/edit the mask directly. Still great tool. Thanks

**Comment by ride5k** [comment]
> or if you could paint/edit the mask directly. Still great tool. Thanks

this would be a fantastic addition, as it occasionally detects "non-faces" and it would be very slick to be able to mask them out

**Comment by Echolink50** [comment]
This would be a great addition if the created mask could be drawn over within gradio. Sometimes the mask is 90% right and you just need to tweak it a little. Thanks for the awesome addon
