### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by realclone1** [djbielejeski/a-person-mask-generator#29]
Error occurred when executing APersonMaskGenerator:

ImageSegmenterOptions.__init__() got an unexpected keyword argument 'output_category_mask'

File "E:\Blender_ComfyUI\ComfyUI\execution.py", line 152, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "E:\Blender_ComfyUI\ComfyUI\execution.py", line 82, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "E:\Blender_ComfyUI\ComfyUI\execution.py", line 75, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "E:\Blender_ComfyUI\ComfyUI\custom_nodes\a-person-mask-generator\a_person_mask_generator_comfyui.py", line 103, in generate_mask
options = mp.tasks.vision.ImageSegmenterOptions(

I really don't know how to solve it

**Comment by djbielejeski** [comment]
Try the following

1. Close ComfyUI 
2. Open CMD and activate your comfyUI virtual environment (for me this is executing `venv\Scripts\activate.bat`)
![image](https://github.com/djbielejeski/a-person-mask-generator/assets/2463282/336fcee6-2892-4d63-bfac-0199455688bf)

3. Navigate to `custom_nodes\a-person-mask-generator` and run `pip install -r requirements.txt`
![image](https://github.com/djbielejeski/a-person-mask-generator/assets/2463282/fbb923f3-f023-4602-b919-ae24bbc82938)

**Comment by Minebook** [comment]
asus tuf gaming f15
After launching the WEB UI with this script, the right speaker breaks and white noise instead of sound, after restarting the computer everything is fixed. What could be the problem?
