### ISSUE TITLE
ForgeUI Problem ? Error running install.py for extension

### ISSUE THREAD

**Issue by EKKIV0K** [djbielejeski/a-person-mask-generator#35]
Issue on the new Update : 
I'm using ForgeUI, it seems that extension have problems, 
let me explain that to you guys, on the last update the Ext worked well for one picture, but seems cannot handle multiple uses.
need to reboot ForgeUi to re-use the extension. it's a real problem.

Here is the returned error from the new update : 

** Error running install.py for extension H:\AI GIT\ForgeUI\extensions\a-person-mask-generator.
*** Command: "H:\AI GIT\ForgeUI\venv\Scripts\python.exe" "H:\AI GIT\ForgeUI\extensions\a-person-mask-generator\install.py"
*** Error code: 1
*** stderr: Traceback (most recent call last):
***   File "H:\AI GIT\ForgeUI\extensions\a-person-mask-generator\install.py", line 19, in <module>
***     from .a_person_mask_generator_comfyui import APersonMaskGenerator
*** ImportError: attempted relative import with no known parent package

My set :
Windows 10
RTX 4090 / I9 14900k / 64Go DDR RAM.

**Comment by EKKIV0K** [comment]
Need to mention that i performed a clean install, by deleting the old ext, and Gclone the new one.

**Comment by djbielejeski** [comment]
This should be resolved. Can you confirm after pulling latest?
