### ISSUE TITLE
Setup Error

### ISSUE THREAD

**Issue by YuGino** [djbielejeski/a-person-mask-generator#36]
*** Error running install.py for extension D:\AI\stable-diffusion-webui\extensions\a-person-mask-generator.
*** Command: "D:\AI\stable-diffusion-webui\venv\Scripts\python.exe" "D:\AI\stable-diffusion-webui\extensions\a-person-mask-generator\install.py"
*** Error code: 1
*** stderr: Traceback (most recent call last):
***   File "D:\AI\stable-diffusion-webui\extensions\a-person-mask-generator\install.py", line 19, in <module>
***     from .a_person_mask_generator_comfyui import APersonMaskGenerator
*** ImportError: attempted relative import with no known parent package

**Comment by djbielejeski** [comment]
This should be resolved.  Can you confirm after pulling latest?
