### ISSUE TITLE
ModuleNotFoundError: No module named 'folder_paths' during extension installation

### ISSUE THREAD

**Issue by thejohnd0e** [djbielejeski/a-person-mask-generator#38]
I am encountering an error ModuleNotFoundError: No module named 'folder_paths'. I followed the installation instructions, but the issue persists.

![Screenshot - 2024-05-27 16 33 44](https://github.com/djbielejeski/a-person-mask-generator/assets/115493464/9063d351-d9ae-4bf3-985b-d26036eba356)

UPD: Removing the extension and reinstalling it helped me, everything is fine.

**Comment by djbielejeski** [comment]
Navigate to `stable-diffusion-webui\extensions\a-person-mask-generator` in a cmd window and run `git pull` then try again
