### ISSUE TITLE
Mask blur

### ISSUE THREAD

**Issue by alexeyugn** [djbielejeski/a-person-mask-generator#4]
Liked your project so much, thank you! And I believe it would be great to add mask blur option (+4 px feathering for example) because I notices the contours appear frequently

**Comment by djbielejeski** [comment]
Added here: https://github.com/djbielejeski/a-person-mask-generator/pull/7

![image](https://github.com/djbielejeski/a-person-mask-generator/assets/2463282/9d68a5be-2e5f-4efd-a6aa-8f821656fda1)
