### ISSUE TITLE
Error when running in ComfyUI

### ISSUE THREAD

**Issue by couleurs** [djbielejeski/a-person-mask-generator#42]
Getting the following error when running in ComfyUI. Any idea what's going on?

![Screenshot 2024-07-17 at 2 40 49 PM](https://github.com/user-attachments/assets/62313262-aca7-4815-a174-814c6fba1658)

**Comment by djbielejeski** [comment]
Download the model

https://storage.googleapis.com/mediapipe-models/image_segmenter/selfie_multiclass_256x256/float32/latest/selfie_multiclass_256x256.tflite

and place it here

`\ComfyUI\models\mediapipe\selfie_multiclass_256x256.tflite`

**Comment by djbielejeski** [comment]
![image](https://github.com/user-attachments/assets/36abea1e-58e5-4c2f-9c46-e09ced7577f9)

**Comment by couleurs** [comment]
Yes sorry for the duplicate, I realize this was already asked before but had already asked. My bad!

**Comment by djbielejeski** [comment]
No worries!
