### ISSUE TITLE
The "hair" mask doesn't recognize a beard

### ISSUE THREAD

**Issue by Osato28** [djbielejeski/a-person-mask-generator#5]
As far as I've noticed, the precision is phenomenal, but the model has a pretty significant limitation:
There is no way to detect facial hair separately, or even as part of the hair.
The extension detects the beard as part of the face.

I'm not sure if it's fixable, since it's caused by Google's mediapipe model and I don't know whether that model can be retrained, but posting it just to be thorough.

Version: commit 443e491.

How to replicate: put an image of a bearded man into img2img and use the extension to first detect hair, then face (skin).

Original image 1:
![image(7)](https://github.com/djbielejeski/a-person-mask-generator/assets/65938107/29d2b604-8b3c-438c-a31e-9c445a8b5311)
Hair:
![image(6)](https://github.com/djbielejeski/a-person-mask-generator/assets/65938107/71d19236-ebec-4444-9c30-04b45475586f)
Face (skin):
![image(8)](https://github.com/djbielejeski/a-person-mask-generator/assets/65938107/c4dbe63c-dc45-4d40-afa1-3dbbb302188e)

Original image 2:
![image(10)](https://github.com/djbielejeski/a-person-mask-generator/assets/65938107/1bb12234-c284-4ec4-b05d-e05715389262)
Hair:
![image(11)](https://github.com/djbielejeski/a-person-mask-generator/assets/65938107/eb376402-5291-4857-a463-9e67ba30701c)
Face (skin):
![image(9)](https://github.com/djbielejeski/a-person-mask-generator/assets/65938107/fddd8802-5c59-4406-a69e-5d3a00cead57)

**Comment by djbielejeski** [comment]
The model we use [selfie_multiclass_256x256.tflite](https://developers.google.com/mediapipe/solutions/vision/image_segmenter#multiclass-model) unfortunately does not support beard masks.  I also don't see any other models that do at this time.
