### ISSUE TITLE
Error Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by mertkemal1131** [djbielejeski/a-person-mask-generator#8]
activating the extension throws Error
Expecting value: line 1 column 1 (char 0) error on webui, after disabling the extension there is no error

**Comment by djbielejeski** [comment]
I can't reproduce.  Can you provide a full stack trace or some sort of relevant information?

**Comment by mertkemal1131** [comment]
![Ekran görüntüsü 2023-11-19 210925](https://github.com/djbielejeski/a-person-mask-generator/assets/113249667/e026955c-4087-4636-bb8e-24ae854731c2)
![Ekran görüntüsü 2023-11-19 210748](https://github.com/djbielejeski/a-person-mask-generator/assets/113249667/45d95f5a-da0f-44f3-9b38-e542d817a64c)
the only error i can provide is this because in cmd there no error message

**Comment by djbielejeski** [comment]
Can you paste the entire console output with the error here?

**Comment by mertkemal1131** [comment]
INCOMPATIBLE PYTHON VERSION

This program is tested with 3.10.6 Python, but you have 3.9.0.
If you encounter an error with "RuntimeError: Couldn't install torch." message,
or any other error regarding unsuccessful package (library) installation,
please downgrade (or upgrade) to the latest version of 3.10 Python
and delete current Python and "venv" folder in WebUI's directory.

You can download 3.10 Python from here: https://www.python.org/downloads/release/python-3106/

Alternatively, use a binary release of WebUI: https://github.com/AUTOMATIC1111/stable-diffusion-webui/releases

Use --skip-python-version-check to suppress this warning.
==============================================================================================================
Python 3.9.0 (tags/v3.9.0:9cf6752, Oct  5 2020, 15:34:40) [MSC v.1927 64 bit (AMD64)]
Version: v1.6.0-2-g4afaaf8a
Commit hash: 4afaaf8a020c1df457bcf7250cb1c7f609699fa7
Launching Web UI with arguments:
no module 'xformers'. Processing without...
no module 'xformers'. Processing without...
No module 'xformers'. Proceeding without it.
Loading weights [ef76aa2332] from C:\Users\mertk\Desktop\fart\stable-diffusion-webui\models\Stable-diffusion\realisticVisionV51_v51VAE.safetensors
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 12.5s (prepare environment: 3.3s, import torch: 3.7s, import gradio: 1.2s, setup paths: 0.8s, initialize shared: 0.5s, other imports: 0.8s, setup codeformer: 0.1s, load scripts: 1.3s, create ui: 0.6s, gradio launch: 0.2s).
Creating model from config: C:\Users\mertk\Desktop\fart\stable-diffusion-webui\configs\v1-inference.yaml
Applying attention optimization: Doggettx... done.
Model loaded in 7.0s (load weights from disk: 0.9s, create model: 0.4s, apply weights to model: 5.0s, apply half(): 0.2s, load VAE: 0.2s, calculate empty prompt: 0.2s).

**Comment by djbielejeski** [comment]
Sounds like you know what to do, install python 3.10.*

**Comment by mertkemal1131** [comment]
how can i do that
